{% set name = "diazo" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/diazo-{{ version }}.tar.gz
  sha256: 5f552e51a53d08d65935805a3cafde25bb8d2ed80867338ce9e9acb8da7f685e

build:
  entry_points:
    - diazocompiler = diazo.compiler:main
    - diazorun = diazo.run:main
    - diazopreprocessor = diazo.rules:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - lxml
    - cssselect
    - six

test:
  imports:
    - diazo
  commands:
    - pip check
    - diazocompiler --help
    - diazorun --help
    - diazopreprocessor --help
  requires:
    - pip

about:
  home: http://diazo.org
  summary: Diazo implements a Deliverance like language using a pure XSLT engine. With Diazo, you "compile" your theme and ruleset in one step, then use a superfast/simple transform on each request thereafter. Alternatively, compile your theme during development, check it into version control, and not touch Diazo during deployment.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
