# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: diazo
  version: "2.0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/diazo-${{ version }}.tar.gz
  sha256: 9825e30e7789da8a14436ee642470c62440a9215d329078beb68b12ff6e3aa2e

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - diazocompiler = diazo.compiler:main
      - diazorun = diazo.run:main
      - diazopreprocessor = diazo.rules:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - webob
    - python >=${{ python_min }},<4.0
    - lxml
    - cssselect

tests:
  - python:
      imports:
        - diazo
      python_version: ${{ python_min }}.*
      pip_check: true
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - diazocompiler --help
      - diazorun --help
      - diazopreprocessor --help

about:
  summary: |
    Diazo implements a Deliverance like language using a pure XSLT engine. With Diazo, you "compile" your theme and ruleset in one step, then use a superfast/simple transform on each request thereafter. Alternatively, compile your theme during development, check it into version control, and not touch Diazo during
    deployment.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: http://diazo.org

extra:
  recipe-maintainers:
    - rxm7706
